model:
  dim: 384
  depth: 12
  stereo: true
  num_stems: 1
  time_transformer_depth: 1
  freq_transformer_depth: 1
  linear_transformer_depth: 0
  # freqs_per_bands: !!python/tuple
  #   - 2
  #   - 2
  #   - 2
  #   - 2
  #   - 2
  #   - 2
  #   - 2
  #   - 2
  #   - 2
  #   - 2
  #   - 2
  #   - 2
  #   - 2
  #   - 2
  #   - 2
  #   - 2
  #   - 2
  #   - 2
  #   - 2
  #   - 2
  #   - 2
  #   - 2
  #   - 2
  #   - 2
  #   - 4
  #   - 4
  #   - 4
  #   - 4
  #   - 4
  #   - 4
  #   - 4
  #   - 4
  #   - 4
  #   - 4
  #   - 4
  #   - 4
  #   - 12
  #   - 12
  #   - 12
  #   - 12
  #   - 12
  #   - 12
  #   - 12
  #   - 12
  #   - 24
  #   - 24
  #   - 24
  #   - 24
  #   - 24
  #   - 24
  #   - 24
  #   - 24
  #   - 48
  #   - 48
  #   - 48
  #   - 48
  #   - 48
  #   - 48
  #   - 48
  #   - 48
  #   - 128
  #   - 129
  dim_head: 48
  heads: 8
  attn_dropout: 0.1
  ff_dropout: 0.1
  flash_attn: true
  dim_freqs_in: 1025
  stft_n_fft: 2048
  stft_hop_length: 441
  stft_win_length: 2048
  stft_normalized: false
  mask_estimator_depth: 2
  multi_stft_resolution_loss_weight: 1.0
  # multi_stft_resolutions_window_sizes: !!python/tuple
  # - 4096
  # - 2048
  # - 1024
  # - 512
  # - 256
  multi_stft_hop_size: 147
  multi_stft_normalized: False

training:
  random_seed: 42
  train_root_dir: "/23SA01/datasets/musdb18hq/train"
  valid_root_dir: "/23SA01/datasets/musdb18hq/test"
  meta_dir: "/23SA01/codes/Music-Source-Separation-BSRoFormer-pl/dataset_meta"
  meta_train: "/23SA01/codes/Music-Source-Separation-BSRoFormer-pl/dataset_meta/data_bleeding_train.json"
  length: 5
  sampler_rate: 44100
  shift: 44100
  seg_len: 352800

  num_epochs: 1500
  num_steps: 1000
  train_batch_size: 2
  valid_batch_size: 1
  grad_accumulate: 8
  num_workers: 32
  use_amp: true

  instruments:
  - vocals

  target_instrument: vocals
  optim:
    lr: 5e-4

inference:
  batch_size: 1
  dim_t: 512
  num_overlap: 4
  seg_len: 352800
  extract_instrumental: false

wandb:
  api_key: # your api key